ALTER TABLE job ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 70;
ALTER TABLE job ADD COLUMN IF NOT EXISTS stage VARCHAR(20) NOT NULL DEFAULT 'queued';
ALTER TABLE job ADD COLUMN IF NOT EXISTS qualities TEXT NOT NULL DEFAULT '[]';
ALTER TABLE upload_session ADD COLUMN IF NOT EXISTS uploaded_bytes BIGINT NOT NULL DEFAULT 0;
INSERT IGNORE INTO schema_version(version) VALUES (3);
