events {}
http {
    access_log off;
    error_log /dev/null;
    resolver 127.0.0.11 valid=5s ipv6=off;
    server {
        listen 8090;
        client_max_body_size 64k;
        location / {
            proxy_set_header Host localhost;
            proxy_set_header Forwarded "";
            proxy_set_header X-Forwarded-For "";
            set $api_backend api:8090;
            proxy_pass http://$api_backend;
        }
    }
    server {
        listen 8091;
        location / {
            proxy_set_header Host localhost;
            proxy_set_header Forwarded "";
            proxy_set_header X-Forwarded-For "";
            proxy_buffering off;
            set $gateway_backend gateway:8091;
            proxy_pass http://$gateway_backend;
        }
    }
}
